<?xml version="1.0"?>
<!-- $Id$ -->

<!--
 ** （複数）用語体系ブラウジングシステムのサービスを行うための WSDL 記述 **
-->

<definitions name="GraphViz"
             targetNamespace="urn:GraphViz"
             xmlns:typens="urn:GraphViz"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
             xmlns="http://schemas.xmlsoap.org/wsdl/">

  <!-- Types  -->

  <!-- Messages -->

  <message name="doGraphViz">
    <part name="dot"          type="xsd:base64Binary"/>
    <part name="format"       type="xsd:string"/>
  </message>

  <message name="doGraphVizResponse">
    <part name="return"       type="xsd:base64Binary"/>
  </message>

  <!-- Port -->

  <portType name="GraphVizPort">

    <operation name="doGraphViz">
      <input message="typens:doGraphViz"/>
      <output message="typens:doGraphVizResponse"/>
    </operation>

  </portType>

  <!-- Binding -->

  <binding name="GraphVizBinding" type="typens:GraphVizPort">
    <soap:binding style="rpc"
                  transport="http://schemas.xmlsoap.org/soap/http"/>

    <operation name="doGraphViz">
      <soap:operation soapAction="urn:GraphVizAction"/>
      <input>
        <soap:body use="encoded"
                   namespace="urn:GraphViz"
                   encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
      </input>
      <output>
        <soap:body use="encoded"
                   namespace="urn:GraphViz"
                   encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
      </output>
    </operation>

  </binding>

  <!-- Endpoint -->
  <service name="GraphVizService">
    <port name="GraphVizPort" binding="typens:GraphVizBinding">
      <soap:address location="http://avalon.ulis.ac.jp/~masao/term-viz-ws/GraphVizService.cgi"/>
    </port>
  </service>

</definitions>
